### ISSUE TITLE
Does WP Polls allow "other" answers?

### ISSUE THREAD

**Issue by jackoslam** [lesterchan/gamerz-error_log-cleaner#1]
1. Is there any way to give the poll-taker an opportunity to add a string of text as the answer? I see no way to offer "Other" as an answer.
2. I see all the code for templates, but do I have to be a programmer to alter the template? Is there no user interface with checkboxes, menus, variables, etc. that a non-programmer can use to customize the poll? If not, you ought to include one.

**Comment by lesterchan** [comment]
Wrong Repo.

Nope for both answers, If you need a friendly interface, I will recommend PollDaddy.

**Comment by jackoslam** [comment]
What does Wrong Repo. mean?

Date: Mon, 2 Feb 2015 21:51:30 -0800
